services:
  - type: web
    name: olanexamcbt
    env: python
    buildCommand: pip install -r olanexamscbt-main/requirements.txt
    startCommand: uvicorn olanexamscbt-main.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    autoDeploy: true
